USE_POWERLINE="true"
HAS_WIDECHARS="false"

export GPG_TTY=$(tty)

# Configuración para 16 colores básicos
# 30=negro, 31=rojo, 32=verde, 33=amarillo, 34=azul, 35=magenta, 36=cyan, 37=blanco
# Agregando 1; hace el color brillante (colores 8-15)
export LS_COLORS="di=1;34:ln=1;36:so=1;35:pi=33:ex=1;32:bd=34:cd=33:su=37;41:sg=30;43:tw=30;42:ow=34:*.tar=1;31:*.tgz=1;31:*.zip=1;31:*.gz=1;31:*.bz2=1;31:*.7z=1;31:*.rar=1;31:*.deb=1;31:*.rpm=1;31:*.jpg=1;35:*.jpeg=1;35:*.gif=1;35:*.png=1;35:*.svg=1;35:*.mp4=1;35:*.mkv=1;35:*.avi=1;35:*.mp3=1;36:*.flac=1;36:*.wav=1;36:*.pdf=33:*.doc=33:*.txt=37:*.md=33:*.conf=37:*.yml=37:*.json=37:*.xml=37:*.py=32:*.js=32:*.ts=32:*.html=32:*.css=32:*.sh=32:*.go=32:*.rs=32"

if ls --color > /dev/null 2>&1; then
  alias ls='ls --color=auto'
else
  export CLICOLOR=1
  export LSCOLORS=ExFxBxDxCxegedabagacad
  alias ls='ls -G'
fi

zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# --- Navegación inteligente del historial ---
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

if [[ -n "${terminfo[kcuu1]}" ]]; then
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Configuración de syntax highlighting para 16 colores
# Colores disponibles: black, red, green, yellow, blue, magenta, cyan, white
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red'
ZSH_HIGHLIGHT_STYLES[error]='fg=red,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=yellow,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=green'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=green'
ZSH_HIGHLIGHT_STYLES[function]='fg=green'
ZSH_HIGHLIGHT_STYLES[command]='fg=green'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=white'
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[path_approx]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=blue'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=blue'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=white'
ZSH_HIGHLIGHT_STYLES[comment]='fg=black,bold'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=green'
